version: "3"

services:
  mysql:
    # image: mysql/mysql-server:5.7
    image: mysql:latest
    platform: linux/amd64
    volumes:
      - v_mysql:/var/lib/mysql
      # - ./v_mysql/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    ports:
      # ポートを指定し、外部から接続させる
      - "3306:3306"
    # restart: always
    env_file: .env

  wordpress:
    depends_on:
      - mysql
    build: ./docker/wordpress
    volumes:
      # - ./html:/var/www/html
      - v_wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    # restart: always
    environment:
      TZ: "Asia/Tokyo"
      WORDPRESS_DB_HOST: mysql:3306
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    # restart: always
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "mysql"

    ports:
      - 8888:80

  wpcli:
    container_name: wpcli
    image: wordpress:cli-php7.4
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - mysql
    volumes:
      - v_wordpress:/var/www/html
    command: "--info"
    user: xfs

volumes:
  v_mysql:
  v_wordpress:
